name: Zip and copy to S3

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - master
    paths-ignore:
    - '.github/**'
    - '.gitignore'
    - '*.md'
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      
      # Runs a single command using the runners shell
      - name: Zip
        run: cd $GITHUB_WORKSPACE && zip -r /tmp/artifact.zip . -x .git/\* -x .github/\* -x .gitignore
      
      - name: Configure AWS credentials for Ops Account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: 'arn:aws:iam::408325613969:role/Github_Federated_Access_Role'
          aws-region: 'ap-southeast-2'
        
      - name: Upload to S3
        run: aws s3 cp --sse AES256 /tmp/artifact.zip s3://smops-replica-master/artifacts/backends/express-token-server/${GITHUB_REF_NAME}/Content.zip
